name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk libffi-dev libssl-dev autoconf automake build-essential libtool pkg-config zlib1g-dev

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      # --- КЭШ --- 
      - name: Cache .buildozer
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-buildozer-

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('buildozer.spec') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Clean old buildozer cache
        run: rm -rf .buildozer/android/platform

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install required Android packages
        run: |
          yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager \
            "platforms;android-34" \
            "platform-tools" \
            "build-tools;34.0.0"

      - name: Build with Buildozer
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Konkord-APK
          path: bin/*.apk