name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get install -y zip unzip openjdk-17-jdk libffi-dev libssl-dev autoconf automake build-essential libtool pkg-config zlib1g-dev

      - name: Install Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Accept Android SDK licenses
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android Build Tools
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;34.0.0"

      - name: Build with Buildozer
        run: buildozer android debug